#pragma once
#include "./base/camera.hpp"
#include "./base/ray.hpp"
#include "./base/material.hpp"
#include "./base/primitive.hpp"
#include "./base/light.hpp"
#include "./base/framebuffer.hpp"
#include "./utils/scene_io.hpp"
#include "./base/texture.hpp"
#include "./method/whitted.hpp"
#include "./method/roulette_naive.hpp"
#include "./scene_func/scenes.hpp"
#include <omp.h>
